server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:apostas;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    enabled: true

logging:
  level:
    "org.springframework.web": "INFO"
