CREATE TABLE avaliacoes (
  id BIGSERIAL PRIMARY KEY,
  usuario_id BIGINT NOT NULL,
  gasto_total DECIMAL(12,2) NOT NULL,
  risco VARCHAR(10) NOT NULL,
  criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
